
ofertas = [
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO ANHANGUERA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UniEnsino', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE ANHANGUERA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PROMOVE', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE COMUNITARIA EFAPI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario de Excelência Eniac', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CESUMAR', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario CEUNI FAMETR', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO DISTRITO FEDERAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE QI BRASIL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE METROPOLITANA DO CEARA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DESCOMPLICA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE SETE LAGOAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'ESCOLA SUPERIOR NACIONAL DE SEGUROS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Uniao das Americas Descomplica', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CRUZEIRO DO SUL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DAS FACULDADES METROPOLITANAS UNIDAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO GAMA E SOUZA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO NORTE', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO DISTRITO FEDERAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE VOLTA REDONDA (UNIFOA)', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE SENAC', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Fametro', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DO NOROESTE DE MINAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE ENSINO SUPERIOR PELEGRINO CIPRIANI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE ACESITA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE CNEC RIO DAS OSTRAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DO VALE DO JAGUARIBE', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'FACULDADE JARDINS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE DO OESTE DE SANTA CATARINA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CRUZEIRO DO SUL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO METODISTA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Universidade Universus Veritas Guarulhos', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE VIA SAPIENS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE SANTA MARCELINA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE CIENCIAS SOCIAIS APLICADAS DE SINOP', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO CENTRAL PAULISTA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE DA AMAZONIA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CIDADE DE SAO PAULO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITÁRIO FILADELFIA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE BOTUCATU', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO ESPIRITO SANTO', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADES INTEGRADAS SAO PEDRO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO ATENAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE DO OESTE DE SANTA CATARINA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Uniao das Americas Descomplica', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE UNIFAMETRO CASCAVEL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Universidade Universus Veritas Guarulhos', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CESUMAR', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE CRUZEIRO DO SUL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO SUL DE MINAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE AMERICANA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Uniao das Americas Descomplica', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UniEnsino', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNICATOLICA', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'ULBRA CACHOEIRA DO SUL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'Centro Universitario de Excelencia', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario de Excelencia', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO FILADELFIA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE MURIALDO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Uniao das Americas Descomplica', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Universidade Universus Veritas Guarulhos', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE BRAZ CUBAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTEGRADO DE CAMPO MOURAO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO ANHANGUERA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO ESPIRITO SANTO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UniEnsino', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Universidade Universus Veritas Guarulhos', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE ANHANGUERA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE DE UBERABA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO IMEPAC', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PROMOVE', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE UNIFAMETRO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE CIENCIAS HUMANAS ESUDA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DESCOMPLICA', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO UNIFTEC', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UniEnsino', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE MURIALDO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO SUL DE MINAS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE CIENCIAS E EMPREENDEDORISMO', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE CRUZEIRO DO SUL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'FACULDADE QI BRASIL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO FACENS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE SETE LAGOAS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE JOAO PESSOA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTEGRADO DE CAMPO MOURAO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario Uniao das Americas Descomplica', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'Centro Universitario Funorte', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DESCOMPLICA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE CIENCIAS E EMPREENDEDORISMO', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UNIVERSIDADE METODISTA DE PIRACICABA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO UNIRB', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE JARDINS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Centro Universitario de Excelencia', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO DISTRITO FEDERAL', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'UniEnsino', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'FACULDADE TRES MARIA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE DE AMERICANA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CESUMAR', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'FACULDADE DE TECNOLOGIA ALTOMEDIO SAO FRANCISCO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADES INTEGRADAS HELIO ALONSO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO FILADELFIA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO INTERNACIONAL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CESUMAR', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE PITAGORAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO FAEL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DO NORTE', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE CESUMA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO METODISTA', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'Faculdades Sulamerica Bahia', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE GOIAS', 'ano': 2022, 'modalidade': 'ead'},
    {'instituicao': 'CENTRO UNIVERSITARIO LEONARDO DA VINCI', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'CENTRO UNIVERSITARIO DE CIENCIAS E EMPREENDEDORISMO', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'FACULDADE TRES MARIAS', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE LUTERANA DO BRASIL', 'ano': 2022, 'modalidade': 'presencial'},
    {'instituicao': 'UNIVERSIDADE DA AMAZONIA', 'ano': 2022, 'modalidade': 'ead'},
]

def estatisticas_ofertas_por_modalidade(ofertas, ano, modalidade):
    ofertas_filtradas = [oferta for oferta in ofertas if oferta['ano'] == ano and oferta['modalidade'] == modalidade]

    if not ofertas_filtradas:
        return None  # Caso não haja ofertas para o ano e modalidade especificados

    contagem_por_instituicao = Counter(oferta['instituicao'] for oferta in ofertas_filtradas)
    
    return contagem_por_instituicao

ano_desejado = 2022
modalidade_desejada = 'presencial'
resultado = estatisticas_ofertas_por_modalidade(ofertas, ano_desejado, modalidade_desejada)

if resultado:
    print(f"Estatísticas para o ano {ano_desejado} e modalidade {modalidade_desejada}:\n")
    for instituicao, quantidade in resultado.items():
        print(f"{instituicao}: {quantidade} oferta(s)")
else:
    print(f"Nenhuma oferta encontrada para o ano {ano_desejado} e modalidade {modalidade_desejada}.")
